In [252]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso,RidgeCV, LassoCV, ElasticNet, ElasticNetCV

In [253]:
data=pd.read_csv("C:\\Users\\REVANTH\\Downloads\\energydata_complete.csv",parse_dates=['date'])

In [254]:
data.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0 2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1 2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2 2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3 2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4 2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [255]:
data.shape

(19735, 29)

In [256]:
x=data['T2']
y=data['T6']
x=x.values.reshape(-1,1)
y=y.values.reshape(-1,1)
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

lin=LinearRegression()
lin.fit(x_train,y_train)
pre=lin.predict(x_test)
pre


array([[3.41391863],
       [8.01873204],
       [3.13911525],
       ...,
       [9.2961964 ],
       [8.26382694],
       [5.87229482]])

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [258]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X=data.drop(columns=["date","lights"])
Y=data['Appliances']
#X=X.values.reshape(-1,1)
#Y=Y.values.reshape(-1,1)

In [259]:
scaler=MinMaxScaler()
X_SCALED=scaler.fit_transform(X)


In [260]:
x_train,x_test,y_train,y_test = train_test_split(X_SCALED,Y,test_size = 0.3,random_state=352)

In [261]:
lin=LinearRegression()
lin.fit(x_train,y_train)

LinearRegression()

In [262]:
predi=lin.predict(x_test)
predi

array([ 40., 100.,  60., ...,  50., 100.,  30.])

In [278]:
mae = mean_absolute_error(y_test, predi)
round(mae, 2)

0.0

In [264]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predi))
round(rmse, 3)

0.0

In [265]:
lin.score(x_test,y_test)

1.0

In [266]:
# Residual Sum of Squares (RSS)
import numpy as np
rss = np.sum(np.square(y_test - pre))
round(rss, 3) 

ValueError: Data must be 1-dimensional

In [ ]:
Adj_r2 = 1 - (1-r2_score(y_test, predi)) * (len(y)-1)/(len(y)-X.shape[1]-1)

In [ ]:
# Root Mean Square Error (RMSE)
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, pre))
round(rmse, 3)

In [267]:
#from sklearn.metrics import r2_score
r2_score = r2_score(y_test, pre)
round(r2_score, 3) 

TypeError: 'numpy.float64' object is not callable

In [268]:
ridge_model = Ridge(alpha=0.4)
ridge_model.fit(x_train, y_train)

Ridge(alpha=0.4)

In [269]:
p=ridge_model.predict(x_test)
p

array([ 40.05609914,  99.95785333,  60.20816078, ...,  50.03889907,
       100.04573551,  30.18089947])

In [283]:
ridge_model.coef_

array([ 1.06603701e+03, -8.72270548e-02,  2.02555303e+00, -8.91027815e-01,
       -1.79892259e+00,  1.12254164e+00,  3.96672770e-01,  1.08451193e-01,
        2.03109781e-01, -4.38461388e-02,  6.63172932e-02,  8.57935363e-01,
        7.62876409e-02,  3.36683561e-02, -1.74814389e-01,  4.13256178e-01,
       -6.52124349e-01, -7.35765500e-01, -1.36072246e-01, -9.25269219e-01,
        2.15368932e-02, -9.63573439e-02,  1.20246623e-01,  3.46983212e-02,
        2.37022335e-01, -7.59225610e-03, -7.59225610e-03])

In [270]:
rms = np.sqrt(mean_squared_error(y_test, p))
round(rmse, 3) 

0.0

In [271]:
rmse = np.sqrt(mean_squared_error(y_test, pre))
round(rmse, 3) 

137.667

In [284]:
lasso_reg.coef_

array([1069.89018764,    0.        ,    0.        ,    0.        ,
         -0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
         -0.        ,    0.        ,   -0.        ,    0.        ,
         -0.        ,    0.        ,   -0.        ,    0.        ,
         -0.        ,   -0.        ,    0.        ,   -0.        ,
          0.        ,   -0.        ,   -0.        ])

In [290]:
lasso_reg = Lasso(alpha=0.0001)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=0.0001)

In [286]:
pr=lasso_reg.predict(x_test)
pr


array([40.00058783, 99.99997206, 60.00038257, ..., 50.0004852 ,
       99.99997206, 30.00069046])

In [292]:
lasso_reg.coef_

array([1069.98901876,    0.        ,    0.        ,    0.        ,
         -0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
         -0.        ,    0.        ,   -0.        ,    0.        ,
         -0.        ,    0.        ,   -0.        ,    0.        ,
         -0.        ,   -0.        ,    0.        ,   -0.        ,
          0.        ,   -0.        ,   -0.        ])

In [293]:
w=pd.Series(lasso_reg.coef_)
w

0     1069.989019
1        0.000000
2        0.000000
3        0.000000
4       -0.000000
5        0.000000
6        0.000000
7        0.000000
8        0.000000
9        0.000000
10       0.000000
11       0.000000
12      -0.000000
13       0.000000
14      -0.000000
15       0.000000
16      -0.000000
17       0.000000
18      -0.000000
19       0.000000
20      -0.000000
21      -0.000000
22       0.000000
23      -0.000000
24       0.000000
25      -0.000000
26      -0.000000
dtype: float64

In [275]:
rmse = np.sqrt(mean_squared_error(y_test, pr))
round(rmse, 3) 

0.011

In [276]:
weight = pd.Series(lasso_reg.coef_)
weight

0     1069.890188
1        0.000000
2        0.000000
3        0.000000
4       -0.000000
5        0.000000
6        0.000000
7        0.000000
8        0.000000
9        0.000000
10       0.000000
11       0.000000
12      -0.000000
13       0.000000
14      -0.000000
15       0.000000
16      -0.000000
17       0.000000
18      -0.000000
19       0.000000
20      -0.000000
21      -0.000000
22       0.000000
23      -0.000000
24       0.000000
25      -0.000000
26      -0.000000
dtype: float64

In [277]:
rmse = np.sqrt(mean_squared_error(y_test, pre))
round(rmse, 3) 

137.667

In [ ]:
def get_weights_df(model, feat, col_name):
#this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

In [ ]:
lnw=get_weights_df(lin,x_train,'Linear_Model_Weight')

In [ ]:
weights = pd.Series(lin.coef_)

weights



In [ ]:
y=x_test.values

In [ ]:
data.head()